<?php

return [
    'weather' => [
        'endpoints' => [
            'forecast' => env('WEATHER_FORECAST_ENDPOINT', 'https://api.open-meteo.com/v1/'),
            'marine' => env('WEATHER_MARINE_ENDPOINT', 'https://marine-api.open-meteo.com/v1/'),
        ],
    ],
    'name' => env('SCARLET_NAME', 'Scarlet'),
    'passage' => env('SCARLET_PASSAGE', ''),
    'mmsi' => env('SCARLET_MMSI', ''),
    'home' => [
        'name' => env('SCARLET_HOME_NAME', 'UK'),
        'longitude' => env('SCARLET_HOME_LONGITUDE', -0.13853150944904064),
        'latitude' => env('SCARLET_HOME_LATITUDE', 51.53433094575387),
    ],
    'reverb' => [
        'host' => env('REVERB_PUBLIC_HOST', ''),
        'port' => (int) env('REVERB_PUBLIC_PORT', 443),
        'scheme' => env('REVERB_PUBLIC_SCHEME', 'https'),
    ],
    'mediamtx' => [
        'api_url' => env('MEDIAMTX_API_URL', 'http://mediamtx:9997'),
    ],
    'metrics' => [
        'prometheus_url' => env('PROMETHEUS_URL', 'http://victoriametrics:8428'),
        'push_interval' => (int) env('METRICS_PUSH_INTERVAL', 15),

        'battery' => [
            'min_voltage' => (float) env('BATTERY_MIN_VOLTAGE', 10.0),
            'max_voltage' => (float) env('BATTERY_MAX_VOLTAGE', 14.4),
        ],

        'mappings' => [
            'boat' => [
                // Navigation
                'speed_sog' => 'scarlet_signalk_navigation_speedOverGround * 1.94384',
                'speed_stw' => 'scarlet_signalk_navigation_speedThroughWater * 1.94384',
                'heading' => 'scarlet_signalk_navigation_headingTrue * 180 / 3.14159265359',
                'cog' => 'scarlet_signalk_navigation_courseOverGroundTrue * 180 / 3.14159265359',
                'depth' => 'scarlet_signalk_environment_depth_belowSurface',
                'heel' => 'scarlet_signalk_navigation_attitude_roll * 180 / 3.14159265359',
                'trip_log' => 'scarlet_signalk_navigation_trip_log / 1852',
                'nav_wp_distance' => 'scarlet_signalk_navigation_courseGreatCircle_nextPoint_distance / 1852',
                'nav_wp_ttg' => 'scarlet_signalk_navigation_courseGreatCircle_nextPoint_timeToGo',

                // Wind (apparent from Signal K, true computed from apparent + STW + heading)
                'wind_speed_apparent' => 'scarlet_signalk_environment_wind_speedApparent * 1.94384',
                'wind_angle_apparent' => 'scarlet_signalk_environment_wind_angleApparent * 180 / 3.14159265359',
                '_aws' => 'scarlet_signalk_environment_wind_speedApparent',
                '_awa' => 'scarlet_signalk_environment_wind_angleApparent',
                '_stw' => 'scarlet_signalk_navigation_speedThroughWater',
                '_heading' => 'scarlet_signalk_navigation_headingTrue',

                // Environment
                'water_temp' => 'scarlet_signalk_environment_water_temperature - 273.15',

                // Batteries (Signal K: bank 0 = house, bank 1 = engine)
                'house_battery_voltage' => 'scarlet_signalk_electrical_batteries_0_voltage',
                'house_battery_soc' => 'scarlet_signalk_electrical_batteries_0_capacity_stateOfCharge * 100',
                'house_battery_current' => 'scarlet_signalk_electrical_batteries_0_current',
                'house_battery_time_remaining' => 'scarlet_signalk_electrical_batteries_0_capacity_timeRemaining / 3600',
                'engine_battery_voltage' => 'scarlet_signalk_electrical_batteries_1_voltage',

                // Tanks
                'fuel_level' => 'scarlet_signalk_tanks_fuel_currentLevel * 100',
                'water_level' => 'scarlet_mqtt_percent{topic="watertank"}',

                // Cabin environment (Zigbee sensors via MQTT)
                'cabin_temp_quarterberth' => 'scarlet_mqtt_temperature{topic="zigbee2mqtt/Quarterberth"}',
                'cabin_humidity_quarterberth' => 'scarlet_mqtt_humidity{topic="zigbee2mqtt/Quarterberth"}',
                'cabin_temp_main' => 'scarlet_mqtt_temperature{topic="zigbee2mqtt/Main Cabin"}',
                'cabin_humidity_main' => 'scarlet_mqtt_humidity{topic="zigbee2mqtt/Main Cabin"}',
                'cabin_temp_forepeak' => 'scarlet_mqtt_temperature{topic="zigbee2mqtt/Forepeak cabin"}',
                'cabin_humidity_forepeak' => 'scarlet_mqtt_humidity{topic="zigbee2mqtt/Forepeak cabin"}',
                'cabin_pressure_forepeak' => 'scarlet_mqtt_pressure{topic="zigbee2mqtt/Forepeak cabin"}',
            ],

            'tracker' => [
                'battery_voltage' => 'scarlet_system_battery_voltage_volts',
                'usb_powered' => 'scarlet_system_usb_powered',
                'lte_connected' => 'scarlet_system_lte_connected',
                'lte_rssi' => 'scarlet_system_lte_rssi_dBm',
                'lte_signal_quality' => 'scarlet_system_lte_signal_quality',
                'lte_rat' => 'scarlet_system_lte_rat',
                'wifi_connected' => 'scarlet_system_wifi_connected',
                'wifi_rssi' => 'scarlet_system_wifi_rssi_dBm',
                'uptime' => 'scarlet_system_uptime_seconds',
                'heap_free' => 'scarlet_system_free_heap_bytes',
                'mode' => 'scarlet_system_mode',
                'cabin_temp' => 'scarlet_mqtt_temperature{topic="zigbee2mqtt/Forepeak cabin"}',
                'cabin_humidity' => 'scarlet_mqtt_humidity{topic="zigbee2mqtt/Forepeak cabin"}',
                'cpu_usage' => 'scarlet_system_cpu_usage_percent',
            ],

            'gps' => [
                'latitude' => 'max(scarlet_gps_latitude_deg{gps_source="signalk"} != 0) default max(scarlet_gps_latitude_deg{gps_source="onboard"} != 0)',
                'longitude' => 'max(scarlet_gps_longitude_deg{gps_source="signalk"} != 0) default max(scarlet_gps_longitude_deg{gps_source="onboard"} != 0)',
                'altitude' => 'scarlet_gps_altitude_meters',
                'satellites' => 'scarlet_gps_satellites',
                'hdop' => 'scarlet_gps_hdop',
                'speed' => 'scarlet_gps_speed_kn',
                'heading' => 'scarlet_gps_heading_deg',
            ],

            'track' => [
                'latitude' => 'scarlet_gps_latitude_deg{device_mode="realtime",gps_source="signalk"} != 0',
                'longitude' => 'scarlet_gps_longitude_deg{device_mode="realtime",gps_source="signalk"} != 0',
                'sog' => '(scarlet_signalk_navigation_speedOverGround * 1.94384) default scarlet_gps_speed_kn',
            ],

            'explore' => [
                // Navigation
                'speed' => [
                    'label' => 'Speed (SOG)',
                    'unit' => 'kn',
                    'color' => 'oklch(0.54 0.22 27)',
                    'query' => 'max(scarlet_signalk_navigation_speedOverGround) * 1.94384',
                    'fallback' => 'max(keep_last_value(scarlet_gps_speed_kn))',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['stw'],
                ],
                'stw' => [
                    'label' => 'Speed (STW)',
                    'unit' => 'kn',
                    'color' => 'oklch(0.42 0.14 178)',
                    'query' => 'max(scarlet_signalk_navigation_speedThroughWater) * 1.94384',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['speed'],
                ],
                'heading' => [
                    'label' => 'Heading',
                    'unit' => '°',
                    'color' => 'oklch(0.42 0.14 178)',
                    'query' => 'max(scarlet_signalk_navigation_headingTrue) * 180 / 3.14159265359',
                    'fallback' => 'max(scarlet_signalk_navigation_headingMagnetic) * 180 / 3.14159265359',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'dashboard_indicator' => 'mini_compass',
                    'related' => ['cog', 'heading_magnetic'],
                ],
                'heading_magnetic' => [
                    'label' => 'Heading (Magnetic)',
                    'unit' => '°',
                    'color' => 'oklch(0.55 0.12 178)',
                    'query' => 'max(scarlet_signalk_navigation_headingMagnetic) * 180 / 3.14159265359',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'related' => ['heading', 'cog'],
                ],
                'cog' => [
                    'label' => 'Course Over Ground',
                    'unit' => '°',
                    'color' => 'oklch(0.55 0.15 240)',
                    'query' => 'max(scarlet_signalk_navigation_courseOverGroundTrue) * 180 / 3.14159265359',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'dashboard_indicator' => 'mini_compass',
                    'related' => ['heading'],
                ],
                'depth' => [
                    'label' => 'Depth',
                    'unit' => 'm',
                    'color' => 'oklch(0.42 0.14 245)',
                    'query' => 'max(scarlet_signalk_environment_depth_belowSurface)',
                    'group' => 'navigation',
                    'type' => 'inverted',
                ],
                'heel' => [
                    'label' => 'Heel',
                    'unit' => '°',
                    'color' => 'oklch(0.48 0.17 70)',
                    'query' => 'max(scarlet_signalk_navigation_attitude_roll) * 180 / 3.14159265359',
                    'group' => 'navigation',
                    'type' => 'signed',
                    'related' => ['pitch'],
                ],
                'pitch' => [
                    'label' => 'Pitch',
                    'unit' => '°',
                    'color' => 'oklch(0.60 0.16 240)',
                    'query' => 'max(scarlet_signalk_navigation_attitude_pitch) * 180 / 3.14159265359',
                    'group' => 'navigation',
                    'type' => 'signed',
                    'related' => ['heel'],
                ],
                'trip_log' => [
                    'label' => 'Trip Log',
                    'unit' => 'nm',
                    'color' => 'oklch(0.42 0.14 178)',
                    'query' => 'max(scarlet_signalk_navigation_trip_log) / 1852',
                    'group' => 'navigation',
                    'type' => 'standard',
                ],
                'nav_wp_distance' => [
                    'label' => 'Distance to Waypoint',
                    'unit' => 'nm',
                    'color' => 'oklch(0.55 0.15 240)',
                    'query' => 'max(scarlet_signalk_navigation_courseGreatCircle_nextPoint_distance) / 1852',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['nav_wp_ttg'],
                ],
                'nav_wp_ttg' => [
                    'label' => 'Time to Waypoint',
                    'unit' => 's',
                    'color' => 'oklch(0.60 0.16 240)',
                    'query' => 'max(scarlet_signalk_navigation_courseGreatCircle_nextPoint_timeToGo)',
                    'group' => 'navigation',
                    'type' => 'duration',
                    'related' => ['nav_wp_distance'],
                ],

                // Wind
                'wind_speed_true' => [
                    'label' => 'True Wind Speed',
                    'unit' => 'kn',
                    'color' => 'oklch(0.54 0.22 27)',
                    'computed' => 'true_wind_speed',
                    'group' => 'wind',
                    'type' => 'standard',
                    'related' => ['wind_speed_apparent', 'wind_direction_true'],
                ],
                'wind_direction_true' => [
                    'label' => 'True Wind Direction',
                    'unit' => '°',
                    'color' => 'oklch(0.65 0.18 40)',
                    'computed' => 'true_wind_direction',
                    'group' => 'wind',
                    'type' => 'compass',
                    'related' => ['wind_angle_apparent', 'wind_speed_true'],
                ],
                'wind_speed_apparent' => [
                    'label' => 'Apparent Wind Speed',
                    'unit' => 'kn',
                    'color' => 'oklch(0.60 0.16 330)',
                    'query' => 'max(scarlet_signalk_environment_wind_speedApparent) * 1.94384',
                    'group' => 'wind',
                    'type' => 'standard',
                    'related' => ['wind_speed_true', 'wind_angle_apparent'],
                ],
                'wind_angle_apparent' => [
                    'label' => 'Apparent Wind Angle',
                    'unit' => '°',
                    'color' => 'oklch(0.60 0.16 330)',
                    'query' => 'max(scarlet_signalk_environment_wind_angleApparent) * 180 / 3.14159265359',
                    'group' => 'wind',
                    'type' => 'compass',
                    'related' => ['wind_direction_true', 'wind_speed_apparent'],
                ],

                // Power
                'battery_soc' => [
                    'label' => 'Battery SOC',
                    'unit' => '%',
                    'color' => 'oklch(0.62 0.15 155)',
                    'query' => 'max(scarlet_signalk_electrical_batteries_0_capacity_stateOfCharge) * 100',
                    'group' => 'power',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['battery_voltage', 'battery_power', 'battery_current'],
                ],
                'battery_power' => [
                    'label' => 'Battery Power',
                    'unit' => 'W',
                    'color' => 'oklch(0.62 0.15 155)',
                    'query' => 'max(scarlet_signalk_electrical_batteries_0_current) * max(scarlet_signalk_electrical_batteries_0_voltage)',
                    'group' => 'power',
                    'type' => 'signed',
                    'related' => ['battery_voltage', 'battery_soc', 'battery_current'],
                ],
                'battery_voltage' => [
                    'label' => 'Battery Voltage',
                    'unit' => 'V',
                    'color' => 'oklch(0.62 0.15 155)',
                    'query' => 'max(scarlet_signalk_electrical_batteries_0_voltage)',
                    'group' => 'power',
                    'type' => 'standard',
                    'related' => ['battery_soc', 'engine_battery_voltage'],
                ],
                'battery_current' => [
                    'label' => 'Battery Current',
                    'unit' => 'A',
                    'color' => 'oklch(0.65 0.18 40)',
                    'query' => 'max(scarlet_signalk_electrical_batteries_0_current)',
                    'group' => 'power',
                    'type' => 'signed',
                    'related' => ['battery_power', 'battery_voltage'],
                ],
                'engine_battery_voltage' => [
                    'label' => 'Engine Battery',
                    'unit' => 'V',
                    'color' => 'oklch(0.65 0.18 40)',
                    'query' => 'max(scarlet_signalk_electrical_batteries_1_voltage)',
                    'group' => 'power',
                    'type' => 'standard',
                    'related' => ['battery_voltage'],
                ],

                // Cabin
                'temp_main_cabin' => [
                    'label' => 'Temp: Main Cabin',
                    'unit' => '°C',
                    'color' => 'oklch(0.65 0.18 330)',
                    'query' => 'max(keep_last_value(scarlet_mqtt_temperature{topic="zigbee2mqtt/Main Cabin"}))',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_forepeak', 'temp_quarterberth'],
                ],
                'temp_forepeak' => [
                    'label' => 'Temp: Forepeak',
                    'unit' => '°C',
                    'color' => 'oklch(0.70 0.14 70)',
                    'query' => 'max(keep_last_value(scarlet_mqtt_temperature{topic="zigbee2mqtt/Forepeak cabin"}))',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_main_cabin', 'temp_quarterberth'],
                ],
                'temp_quarterberth' => [
                    'label' => 'Temp: Quarterberth',
                    'unit' => '°C',
                    'color' => 'oklch(0.60 0.16 240)',
                    'query' => 'max(keep_last_value(scarlet_mqtt_temperature{topic="zigbee2mqtt/Quarterberth"}))',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_main_cabin', 'temp_forepeak'],
                ],
                'humidity_forepeak' => [
                    'label' => 'Humidity: Forepeak',
                    'unit' => '%',
                    'color' => 'oklch(0.70 0.14 70)',
                    'query' => 'max(keep_last_value(scarlet_mqtt_humidity{topic="zigbee2mqtt/Forepeak cabin"}))',
                    'group' => 'cabin',
                    'type' => 'gauge',
                    'related' => ['humidity_main_cabin', 'humidity_quarterberth'],
                ],
                'humidity_quarterberth' => [
                    'label' => 'Humidity: Quarterberth',
                    'unit' => '%',
                    'color' => 'oklch(0.60 0.16 240)',
                    'query' => 'max(keep_last_value(scarlet_mqtt_humidity{topic="zigbee2mqtt/Quarterberth"}))',
                    'group' => 'cabin',
                    'type' => 'gauge',
                ],
                'humidity_main_cabin' => [
                    'label' => 'Humidity: Main Cabin',
                    'unit' => '%',
                    'color' => 'oklch(0.65 0.18 330)',
                    'query' => 'max(keep_last_value(scarlet_mqtt_humidity{topic="zigbee2mqtt/Main Cabin"}))',
                    'group' => 'cabin',
                    'type' => 'gauge',
                ],
                'pressure_forepeak' => [
                    'label' => 'Barometric Pressure',
                    'unit' => 'hPa',
                    'color' => 'oklch(0.55 0.15 240)',
                    'query' => 'max(keep_last_value(scarlet_mqtt_pressure{topic="zigbee2mqtt/Forepeak cabin"}))',
                    'group' => 'cabin',
                    'type' => 'standard',
                ],

                // Environment
                'water_temp' => [
                    'label' => 'Sea Water Temperature',
                    'unit' => '°C',
                    'color' => 'oklch(0.55 0.15 240)',
                    'query' => 'max(scarlet_signalk_environment_water_temperature) - 273.15',
                    'group' => 'environment',
                    'type' => 'standard',
                ],

                // Tanks
                'fuel_level' => [
                    'label' => 'Diesel',
                    'unit' => '%',
                    'color' => 'oklch(0.48 0.17 70)',
                    'query' => 'max(scarlet_signalk_tanks_fuel_currentLevel) * 100',
                    'group' => 'tanks',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['water_level'],
                ],
                'water_level' => [
                    'label' => 'Fresh Water',
                    'unit' => '%',
                    'color' => 'oklch(0.42 0.14 245)',
                    'query' => 'max(keep_last_value(scarlet_mqtt_percent{topic="watertank"}))',
                    'group' => 'tanks',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['fuel_level'],
                ],

                // Tracker
                'gps_satellites' => [
                    'label' => 'GPS Satellites',
                    'unit' => '',
                    'color' => 'oklch(0.62 0.15 155)',
                    'query' => 'max(scarlet_gps_satellites)',
                    'group' => 'tracker',
                    'type' => 'standard',
                ],
                'lte_rssi' => [
                    'label' => 'LTE Signal',
                    'unit' => 'dBm',
                    'color' => 'oklch(0.54 0.22 27)',
                    'query' => 'max(scarlet_system_lte_rssi_dBm)',
                    'group' => 'tracker',
                    'type' => 'standard',
                    'related' => ['wifi_rssi'],
                ],
                'wifi_rssi' => [
                    'label' => 'WiFi Signal',
                    'unit' => 'dBm',
                    'color' => 'oklch(0.55 0.15 240)',
                    'query' => 'max(scarlet_system_wifi_rssi_dBm)',
                    'group' => 'tracker',
                    'type' => 'standard',
                    'related' => ['lte_rssi'],
                ],
                'cpu_usage' => [
                    'label' => 'CPU Usage',
                    'unit' => '%',
                    'color' => 'oklch(0.60 0.16 330)',
                    'query' => 'max(scarlet_system_cpu_usage_percent)',
                    'group' => 'tracker',
                    'type' => 'gauge',
                ],
            ],

            'explore_groups' => [
                'navigation' => [
                    'label' => 'Navigation',
                    'color' => 'oklch(0.42 0.14 178)',
                    'expanded' => true,
                ],
                'wind' => [
                    'label' => 'Wind',
                    'color' => 'oklch(0.48 0.17 70)',
                    'expanded' => false,
                    'headlines' => ['wind_speed_true', 'wind_direction_true', 'wind_speed_apparent', 'wind_angle_apparent'],
                ],
                'power' => [
                    'label' => 'Power',
                    'color' => 'oklch(0.45 0.16 150)',
                    'expanded' => true,
                ],
                'tanks' => [
                    'label' => 'Tanks',
                    'color' => 'oklch(0.48 0.17 70)',
                    'expanded' => true,
                ],
                'cabin' => [
                    'label' => 'Cabin',
                    'color' => 'oklch(0.48 0.17 70)',
                    'expanded' => false,
                    'headlines' => ['temp_main_cabin', 'temp_forepeak', 'pressure_forepeak'],
                ],
                'environment' => [
                    'label' => 'Environment',
                    'color' => 'oklch(0.42 0.14 245)',
                    'expanded' => false,
                    'headlines' => ['water_temp'],
                ],
                'tracker' => [
                    'label' => 'Tracker',
                    'color' => 'oklch(0.52 0.014 205)',
                    'expanded' => false,
                    'headlines' => ['gps_satellites', 'lte_rssi', 'cpu_usage'],
                ],
            ],

            'log' => [
                'latitude' => 'track:latitude',
                'longitude' => 'track:longitude',
                'gps_heading' => 'boat:heading',
                'trip_log' => 'boat:trip_log',
                'aws' => 'boat:_aws',
                'awa' => 'boat:_awa',
                'stw' => 'boat:_stw',
                'heading' => 'boat:_heading',
                'cog' => 'boat:cog',
                'pressure' => 'boat:cabin_pressure_forepeak',
                'wp_distance' => 'boat:nav_wp_distance',
                'wp_ttg' => 'boat:nav_wp_ttg',
                'battery_soc' => 'boat:house_battery_soc',
                'water_level' => 'boat:water_level',
                'fuel_level' => 'boat:fuel_level',
            ],
        ],
    ],
];
