<?php

return [
    'weather' => [
        'endpoints' => [
            'forecast' => env('WEATHER_FORECAST_ENDPOINT', 'https://api.open-meteo.com/v1/'),
            'marine' => env('WEATHER_MARINE_ENDPOINT', 'https://marine-api.open-meteo.com/v1/'),
        ],
    ],
    'name' => env('SCARLET_NAME', 'Scarlet'),
    'passage' => env('SCARLET_PASSAGE', ''),
    'mmsi' => env('SCARLET_MMSI', ''),
    'home' => [
        'name' => env('SCARLET_HOME_NAME', 'UK'),
        'longitude' => env('SCARLET_HOME_LONGITUDE', -0.13853150944904064),
        'latitude' => env('SCARLET_HOME_LATITUDE', 51.53433094575387),
    ],
    'reverb' => [
        'host' => env('REVERB_PUBLIC_HOST', ''),
        'port' => (int) env('REVERB_PUBLIC_PORT', 443),
        'scheme' => env('REVERB_PUBLIC_SCHEME', 'https'),
    ],
    'mediamtx' => [
        'api_url' => env('MEDIAMTX_API_URL', 'http://mediamtx:9997'),
    ],
    'metrics' => [
        'prometheus_url' => env('PROMETHEUS_URL', 'http://victoriametrics:8428'),
        'push_interval' => (int) env('METRICS_PUSH_INTERVAL', 15),

        // How far back the series inventory looks when deciding whether a
        // configured source has "drifted" (genuinely absent) vs is merely
        // offline/stale. Series seen within this window count as present.
        'inventory_lookback_days' => (int) env('METRICS_INVENTORY_LOOKBACK_DAYS', 30),

        'battery' => [
            'min_voltage' => (float) env('BATTERY_MIN_VOLTAGE', 10.0),
            'max_voltage' => (float) env('BATTERY_MAX_VOLTAGE', 14.4),
        ],

        'mappings' => [
            'explore' => [
                'speed' => [
                    'label' => 'Speed (SOG)',
                    'unit' => 'kn',
                    'color' => 'oklch(0.54 0.22 27)',
                    'metric' => 'speed_sog',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['stw'],
                ],
                'stw' => [
                    'label' => 'Speed (STW)',
                    'unit' => 'kn',
                    'color' => 'oklch(0.42 0.14 178)',
                    'metric' => 'speed_stw',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['speed'],
                ],
                'heading' => [
                    'label' => 'Heading',
                    'unit' => '°',
                    'color' => 'oklch(0.42 0.14 178)',
                    'metric' => 'heading',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'dashboard_indicator' => 'mini_compass',
                    'related' => ['cog', 'heading_magnetic'],
                ],
                'heading_magnetic' => [
                    'label' => 'Heading (Magnetic)',
                    'unit' => '°',
                    'color' => 'oklch(0.55 0.12 178)',
                    'metric' => 'heading_magnetic',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'related' => ['heading', 'cog'],
                ],
                'cog' => [
                    'label' => 'Course Over Ground',
                    'unit' => '°',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'cog',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'dashboard_indicator' => 'mini_compass',
                    'related' => ['heading'],
                ],
                'depth' => [
                    'label' => 'Depth',
                    'unit' => 'm',
                    'color' => 'oklch(0.42 0.14 245)',
                    'metric' => 'depth',
                    'group' => 'navigation',
                    'type' => 'inverted',
                ],
                'heel' => [
                    'label' => 'Heel',
                    'unit' => '°',
                    'color' => 'oklch(0.48 0.17 70)',
                    'metric' => 'heel',
                    'group' => 'navigation',
                    'type' => 'signed',
                    'polarity' => ['pos' => 'Starboard', 'neg' => 'Port', 'pos_short' => 'stbd', 'neg_short' => 'port'],
                    'related' => ['pitch'],
                ],
                'pitch' => [
                    'label' => 'Pitch',
                    'unit' => '°',
                    'color' => 'oklch(0.60 0.16 240)',
                    'metric' => 'pitch',
                    'group' => 'navigation',
                    'type' => 'signed',
                    'polarity' => ['pos' => 'Bow up', 'neg' => 'Bow down', 'pos_short' => 'up', 'neg_short' => 'down'],
                    'related' => ['heel'],
                ],
                'trip_log' => [
                    'label' => 'Trip Log',
                    'unit' => 'nm',
                    'color' => 'oklch(0.42 0.14 178)',
                    'metric' => 'trip_log',
                    'group' => 'navigation',
                    'type' => 'standard',
                ],
                'nav_wp_distance' => [
                    'label' => 'Distance to Waypoint',
                    'unit' => 'nm',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'nav_wp_distance',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['nav_wp_ttg'],
                ],
                'nav_wp_ttg' => [
                    'label' => 'Time to Waypoint',
                    'unit' => 's',
                    'color' => 'oklch(0.60 0.16 240)',
                    'metric' => 'nav_wp_ttg',
                    'group' => 'navigation',
                    'type' => 'duration',
                    'related' => ['nav_wp_distance'],
                ],
                'vmg' => [
                    'label' => 'VMG',
                    'unit' => 'kn',
                    'color' => 'oklch(0.58 0.18 160)',
                    'metric' => 'vmg',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['speed', 'nav_wp_distance'],
                ],

                'wind_speed_true' => [
                    'label' => 'True Wind Speed',
                    'unit' => 'kn',
                    'color' => 'oklch(0.54 0.22 27)',
                    'computed' => 'true_wind_speed',
                    'group' => 'wind',
                    'type' => 'standard',
                    'related' => ['wind_speed_apparent', 'wind_direction_true'],
                ],
                'wind_direction_true' => [
                    'label' => 'True Wind Direction',
                    'unit' => '°',
                    'color' => 'oklch(0.65 0.18 40)',
                    'computed' => 'true_wind_direction',
                    'group' => 'wind',
                    'type' => 'compass',
                    'related' => ['wind_angle_apparent', 'wind_speed_true'],
                ],
                'wind_speed_apparent' => [
                    'label' => 'Apparent Wind Speed',
                    'unit' => 'kn',
                    'color' => 'oklch(0.60 0.16 330)',
                    'metric' => 'wind_speed_apparent',
                    'group' => 'wind',
                    'type' => 'standard',
                    'related' => ['wind_speed_true', 'wind_angle_apparent'],
                ],
                'wind_angle_apparent' => [
                    'label' => 'Apparent Wind Angle',
                    'unit' => '°',
                    'color' => 'oklch(0.60 0.16 330)',
                    'metric' => 'wind_angle_apparent',
                    'group' => 'wind',
                    'type' => 'compass',
                    'related' => ['wind_direction_true', 'wind_speed_apparent'],
                ],

                'battery_soc' => [
                    'label' => 'Battery SOC',
                    'unit' => '%',
                    'color' => 'oklch(0.62 0.15 155)',
                    'metric' => 'house_battery_soc',
                    'group' => 'power',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['battery_voltage', 'battery_power', 'battery_current'],
                ],
                'battery_power' => [
                    'label' => 'Battery Power',
                    'unit' => 'W',
                    'color' => 'oklch(0.62 0.15 155)',
                    'computed' => 'battery_power',
                    'group' => 'power',
                    'type' => 'signed',
                    'polarity' => ['pos' => 'Charging', 'neg' => 'Discharging'],
                    'related' => ['battery_voltage', 'battery_soc', 'battery_current'],
                ],
                'battery_voltage' => [
                    'label' => 'Battery Voltage',
                    'unit' => 'V',
                    'color' => 'oklch(0.62 0.15 155)',
                    'metric' => 'house_battery_voltage',
                    'group' => 'power',
                    'type' => 'standard',
                    'related' => ['battery_soc', 'engine_battery_voltage'],
                ],
                'battery_current' => [
                    'label' => 'Battery Current',
                    'unit' => 'A',
                    'color' => 'oklch(0.65 0.18 40)',
                    'metric' => 'house_battery_current',
                    'group' => 'power',
                    'type' => 'signed',
                    'polarity' => ['pos' => 'Charging', 'neg' => 'Discharging'],
                    'related' => ['battery_power', 'battery_voltage'],
                ],
                'engine_battery_voltage' => [
                    'label' => 'Engine Battery',
                    'unit' => 'V',
                    'color' => 'oklch(0.65 0.18 40)',
                    'metric' => 'engine_battery_voltage',
                    'group' => 'power',
                    'type' => 'standard',
                    'related' => ['battery_voltage'],
                ],

                'temp_main_cabin' => [
                    'label' => 'Temp: Main Cabin',
                    'unit' => '°C',
                    'color' => 'oklch(0.65 0.18 330)',
                    'metric' => 'cabin_temp_main',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_forepeak', 'temp_quarterberth'],
                ],
                'temp_forepeak' => [
                    'label' => 'Temp: Forepeak',
                    'unit' => '°C',
                    'color' => 'oklch(0.70 0.14 70)',
                    'metric' => 'cabin_temp_forepeak',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_main_cabin', 'temp_quarterberth'],
                ],
                'temp_quarterberth' => [
                    'label' => 'Temp: Quarterberth',
                    'unit' => '°C',
                    'color' => 'oklch(0.60 0.16 240)',
                    'metric' => 'cabin_temp_quarterberth',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_main_cabin', 'temp_forepeak'],
                ],
                'humidity_forepeak' => [
                    'label' => 'Humidity: Forepeak',
                    'unit' => '%',
                    'color' => 'oklch(0.70 0.14 70)',
                    'metric' => 'cabin_humidity_forepeak',
                    'group' => 'cabin',
                    'type' => 'gauge',
                    'related' => ['humidity_main_cabin', 'humidity_quarterberth'],
                ],
                'humidity_quarterberth' => [
                    'label' => 'Humidity: Quarterberth',
                    'unit' => '%',
                    'color' => 'oklch(0.60 0.16 240)',
                    'metric' => 'cabin_humidity_quarterberth',
                    'group' => 'cabin',
                    'type' => 'gauge',
                ],
                'humidity_main_cabin' => [
                    'label' => 'Humidity: Main Cabin',
                    'unit' => '%',
                    'color' => 'oklch(0.65 0.18 330)',
                    'metric' => 'cabin_humidity_main',
                    'group' => 'cabin',
                    'type' => 'gauge',
                ],
                'pressure_forepeak' => [
                    'label' => 'Barometric Pressure',
                    'unit' => 'hPa',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'cabin_pressure_forepeak',
                    'group' => 'cabin',
                    'type' => 'standard',
                ],

                'water_temp' => [
                    'label' => 'Sea Water Temperature',
                    'unit' => '°C',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'water_temp',
                    'group' => 'environment',
                    'type' => 'standard',
                ],

                'fuel_level' => [
                    'label' => 'Diesel',
                    'unit' => '%',
                    'color' => 'oklch(0.48 0.17 70)',
                    'metric' => 'fuel_level',
                    'group' => 'tanks',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['water_level'],
                ],
                'water_level' => [
                    'label' => 'Fresh Water',
                    'unit' => '%',
                    'color' => 'oklch(0.42 0.14 245)',
                    'metric' => 'water_level',
                    'group' => 'tanks',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['fuel_level'],
                ],

                'gps_satellites' => [
                    'label' => 'GPS Satellites',
                    'unit' => '',
                    'color' => 'oklch(0.62 0.15 155)',
                    'metric' => 'gps_satellites',
                    'group' => 'tracker',
                    'type' => 'standard',
                ],
                'lte_rssi' => [
                    'label' => 'LTE Signal',
                    'unit' => 'dBm',
                    'color' => 'oklch(0.54 0.22 27)',
                    'metric' => 'tracker_lte_rssi',
                    'group' => 'tracker',
                    'type' => 'standard',
                    'related' => ['wifi_rssi'],
                ],
                'wifi_rssi' => [
                    'label' => 'WiFi Signal',
                    'unit' => 'dBm',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'tracker_wifi_rssi',
                    'group' => 'tracker',
                    'type' => 'standard',
                    'related' => ['lte_rssi'],
                ],
                'cpu_usage' => [
                    'label' => 'CPU Usage',
                    'unit' => '%',
                    'color' => 'oklch(0.60 0.16 330)',
                    'metric' => 'tracker_cpu',
                    'group' => 'tracker',
                    'type' => 'gauge',
                ],
            ],

        ],
    ],

    'canonical' => [
        'enabled' => (bool) env('CANONICAL_READER_ENABLED', true),

        // EcoFlow Delta device serial — typed param substituted into canonical EcoFlow source topics.
        'ecoflow_serial' => env('CANONICAL_ECOFLOW_SERIAL', 'P231ZE1APJ3P0446'),
    ],
];
