<?php

return [
    'weather' => [
        'endpoints' => [
            'forecast' => env('WEATHER_FORECAST_ENDPOINT', 'https://api.open-meteo.com/v1/'),
            'marine' => env('WEATHER_MARINE_ENDPOINT', 'https://marine-api.open-meteo.com/v1/'),
        ],
    ],
    'name' => env('SCARLET_NAME', 'Scarlet'),
    'passage' => env('SCARLET_PASSAGE', ''),
    'mmsi' => env('SCARLET_MMSI', ''),
    'home' => [
        'name' => env('SCARLET_HOME_NAME', 'UK'),
        'longitude' => env('SCARLET_HOME_LONGITUDE', -0.13853150944904064),
        'latitude' => env('SCARLET_HOME_LATITUDE', 51.53433094575387),
    ],
    'reverb' => [
        'host' => env('REVERB_PUBLIC_HOST', ''),
        'port' => (int) env('REVERB_PUBLIC_PORT', 443),
        'scheme' => env('REVERB_PUBLIC_SCHEME', 'https'),
    ],
    'mediamtx' => [
        'api_url' => env('MEDIAMTX_API_URL', 'http://mediamtx:9997'),
    ],
    'metrics' => [
        'prometheus_url' => env('PROMETHEUS_URL', 'http://victoriametrics:8428'),
        'push_interval' => (int) env('METRICS_PUSH_INTERVAL', 15),

        'battery' => [
            'min_voltage' => (float) env('BATTERY_MIN_VOLTAGE', 10.0),
            'max_voltage' => (float) env('BATTERY_MAX_VOLTAGE', 14.4),
        ],

        'registry' => [
            'speed_sog' => ['query' => 'scarlet_signalk_navigation_speedOverGround', 'multiply' => 1.94384],
            'speed_stw' => ['query' => 'scarlet_signalk_navigation_speedThroughWater', 'multiply' => 1.94384],
            'heading' => ['query' => 'scarlet_signalk_navigation_headingTrue', 'multiply' => 180, 'divide' => 3.14159265359, 'fallback' => 'scarlet_signalk_navigation_headingMagnetic'],
            'cog' => ['query' => 'scarlet_signalk_navigation_courseOverGroundTrue', 'multiply' => 180, 'divide' => 3.14159265359],
            'depth' => ['query' => 'scarlet_signalk_environment_depth_belowSurface'],
            'heel' => ['query' => 'scarlet_signalk_navigation_attitude_roll', 'multiply' => 180, 'divide' => 3.14159265359],
            'pitch' => ['query' => 'scarlet_signalk_navigation_attitude_pitch', 'multiply' => 180, 'divide' => 3.14159265359],
            'heading_magnetic' => ['query' => 'scarlet_signalk_navigation_headingMagnetic', 'multiply' => 180, 'divide' => 3.14159265359],
            'trip_log' => ['query' => 'scarlet_signalk_navigation_trip_log', 'divide' => 1852],
            'nav_wp_distance' => ['query' => 'scarlet_signalk_navigation_courseGreatCircle_nextPoint_distance', 'divide' => 1852],
            'nav_wp_ttg' => ['query' => 'scarlet_signalk_navigation_courseGreatCircle_nextPoint_timeToGo'],
            'vmg' => ['query' => 'scarlet_signalk_navigation_courseGreatCircle_nextPoint_velocityMadeGood', 'multiply' => 1.94384],

            'wind_speed_apparent_raw' => ['query' => 'scarlet_signalk_environment_wind_speedApparent'],
            'wind_angle_apparent_raw' => ['query' => 'scarlet_signalk_environment_wind_angleApparent'],
            'wind_speed_apparent' => ['query' => 'scarlet_signalk_environment_wind_speedApparent', 'multiply' => 1.94384],
            'wind_angle_apparent' => ['query' => 'scarlet_signalk_environment_wind_angleApparent', 'multiply' => 180, 'divide' => 3.14159265359],

            'speed_stw_raw' => ['query' => 'scarlet_signalk_navigation_speedThroughWater'],
            'heading_raw' => ['query' => 'scarlet_signalk_navigation_headingTrue'],
            'cog_raw' => ['query' => 'scarlet_signalk_navigation_courseOverGroundTrue'],

            'water_temp' => ['query' => 'scarlet_signalk_environment_water_temperature', 'subtract' => 273.15],

            'house_battery_voltage' => ['query' => 'scarlet_signalk_electrical_batteries_0_voltage'],
            'house_battery_soc' => ['query' => 'scarlet_signalk_electrical_batteries_0_capacity_stateOfCharge', 'multiply' => 100],
            'house_battery_current' => ['query' => 'scarlet_signalk_electrical_batteries_0_current'],
            'house_battery_time_remaining' => ['query' => 'scarlet_signalk_electrical_batteries_0_capacity_timeRemaining', 'divide' => 3600],
            'engine_battery_voltage' => ['query' => 'scarlet_signalk_electrical_batteries_1_voltage'],
            'battery_power' => ['computed' => 'battery_power'],

            'fuel_level' => ['query' => 'scarlet_signalk_tanks_fuel_currentLevel', 'multiply' => 100],
            'water_level' => ['query' => 'scarlet_mqtt_percent{topic="watertank"}', 'sticky' => true],

            'cabin_temp_quarterberth' => ['query' => 'scarlet_mqtt_temperature{topic="zigbee2mqtt/Quarterberth"}', 'sticky' => true],
            'cabin_humidity_quarterberth' => ['query' => 'scarlet_mqtt_humidity{topic="zigbee2mqtt/Quarterberth"}', 'sticky' => true],
            'cabin_temp_main' => ['query' => 'scarlet_mqtt_temperature{topic="zigbee2mqtt/Main Cabin"}', 'sticky' => true],
            'cabin_humidity_main' => ['query' => 'scarlet_mqtt_humidity{topic="zigbee2mqtt/Main Cabin"}', 'sticky' => true],
            'cabin_temp_forepeak' => ['query' => 'scarlet_mqtt_temperature{topic="zigbee2mqtt/Forepeak cabin"}', 'sticky' => true],
            'cabin_humidity_forepeak' => ['query' => 'scarlet_mqtt_humidity{topic="zigbee2mqtt/Forepeak cabin"}', 'sticky' => true],
            'cabin_pressure_forepeak' => ['query' => 'scarlet_mqtt_pressure{topic="zigbee2mqtt/Forepeak cabin"}', 'sticky' => true],

            'gps_latitude' => [
                'query' => 'scarlet_gps_latitude_deg{gps_source="signalk"} != 0',
                'fallback' => 'scarlet_gps_latitude_deg{gps_source="onboard"} != 0',
            ],
            'gps_longitude' => [
                'query' => 'scarlet_gps_longitude_deg{gps_source="signalk"} != 0',
                'fallback' => 'scarlet_gps_longitude_deg{gps_source="onboard"} != 0',
            ],
            'gps_altitude' => ['query' => 'scarlet_gps_altitude_meters'],
            'gps_satellites' => ['query' => 'scarlet_gps_satellites'],
            'gps_hdop' => ['query' => 'scarlet_gps_hdop'],
            'gps_speed' => ['query' => 'scarlet_gps_speed_kn'],
            'gps_heading' => ['query' => 'scarlet_gps_heading_deg'],

            'track_latitude' => ['query' => 'scarlet_gps_latitude_deg{device_mode="realtime",gps_source="signalk"} != 0'],
            'track_longitude' => ['query' => 'scarlet_gps_longitude_deg{device_mode="realtime",gps_source="signalk"} != 0'],
            'track_sog' => ['query' => 'scarlet_signalk_navigation_speedOverGround', 'multiply' => 1.94384],

            'tracker_battery' => ['query' => 'scarlet_system_battery_voltage_volts'],
            'tracker_usb' => ['query' => 'scarlet_system_usb_powered'],
            'tracker_lte_connected' => ['query' => 'scarlet_system_lte_connected'],
            'tracker_lte_rssi' => ['query' => 'scarlet_system_lte_rssi_dBm'],
            'tracker_lte_quality' => ['query' => 'scarlet_system_lte_signal_quality'],
            'tracker_lte_rat' => ['query' => 'scarlet_system_lte_rat'],
            'tracker_wifi_connected' => ['query' => 'scarlet_system_wifi_connected'],
            'tracker_wifi_rssi' => ['query' => 'scarlet_system_wifi_rssi_dBm'],
            'tracker_uptime' => ['query' => 'scarlet_system_uptime_seconds'],
            'tracker_heap' => ['query' => 'scarlet_system_free_heap_bytes'],
            'tracker_mode' => ['query' => 'scarlet_system_mode'],
            'tracker_cpu' => ['query' => 'scarlet_system_cpu_usage_percent'],
        ],

        'groups' => [
            'boat' => [
                'speed_sog', 'speed_stw', 'heading', 'cog', 'depth', 'heel',
                'trip_log', 'nav_wp_distance', 'nav_wp_ttg', 'vmg',
                'wind_speed_apparent', 'wind_angle_apparent',
                'wind_speed_apparent_raw', 'wind_angle_apparent_raw',
                'speed_stw_raw', 'heading_raw',
                'water_temp',
                'house_battery_voltage', 'house_battery_soc', 'house_battery_current',
                'house_battery_time_remaining', 'engine_battery_voltage',
                'fuel_level', 'water_level',
                'cabin_temp_quarterberth', 'cabin_humidity_quarterberth',
                'cabin_temp_main', 'cabin_humidity_main',
                'cabin_temp_forepeak', 'cabin_humidity_forepeak',
                'cabin_pressure_forepeak',
            ],
            'tracker' => [
                'tracker_battery', 'tracker_usb', 'tracker_lte_connected',
                'tracker_lte_rssi', 'tracker_lte_quality', 'tracker_lte_rat',
                'tracker_wifi_connected', 'tracker_wifi_rssi',
                'tracker_uptime', 'tracker_heap', 'tracker_mode',
                'cabin_temp_forepeak', 'cabin_humidity_forepeak', 'tracker_cpu',
            ],
            'gps' => [
                'gps_latitude', 'gps_longitude', 'gps_altitude',
                'gps_satellites', 'gps_hdop', 'gps_speed', 'gps_heading',
            ],
            'track' => ['track_latitude', 'track_longitude', 'track_sog'],
            'log' => [
                'track_latitude', 'track_longitude',
                'trip_log', 'wind_speed_apparent_raw', 'wind_angle_apparent_raw',
                'speed_stw_raw', 'heading_raw', 'cog_raw',
                'cabin_pressure_forepeak', 'nav_wp_distance', 'nav_wp_ttg',
                'house_battery_soc', 'water_level', 'fuel_level',
            ],
        ],

        'mappings' => [
            'explore' => [
                'speed' => [
                    'label' => 'Speed (SOG)',
                    'unit' => 'kn',
                    'color' => 'oklch(0.54 0.22 27)',
                    'metric' => 'speed_sog',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['stw'],
                ],
                'stw' => [
                    'label' => 'Speed (STW)',
                    'unit' => 'kn',
                    'color' => 'oklch(0.42 0.14 178)',
                    'metric' => 'speed_stw',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['speed'],
                ],
                'heading' => [
                    'label' => 'Heading',
                    'unit' => '°',
                    'color' => 'oklch(0.42 0.14 178)',
                    'metric' => 'heading',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'dashboard_indicator' => 'mini_compass',
                    'related' => ['cog', 'heading_magnetic'],
                ],
                'heading_magnetic' => [
                    'label' => 'Heading (Magnetic)',
                    'unit' => '°',
                    'color' => 'oklch(0.55 0.12 178)',
                    'metric' => 'heading_magnetic',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'related' => ['heading', 'cog'],
                ],
                'cog' => [
                    'label' => 'Course Over Ground',
                    'unit' => '°',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'cog',
                    'group' => 'navigation',
                    'type' => 'compass',
                    'dashboard_indicator' => 'mini_compass',
                    'related' => ['heading'],
                ],
                'depth' => [
                    'label' => 'Depth',
                    'unit' => 'm',
                    'color' => 'oklch(0.42 0.14 245)',
                    'metric' => 'depth',
                    'group' => 'navigation',
                    'type' => 'inverted',
                ],
                'heel' => [
                    'label' => 'Heel',
                    'unit' => '°',
                    'color' => 'oklch(0.48 0.17 70)',
                    'metric' => 'heel',
                    'group' => 'navigation',
                    'type' => 'signed',
                    'related' => ['pitch'],
                ],
                'pitch' => [
                    'label' => 'Pitch',
                    'unit' => '°',
                    'color' => 'oklch(0.60 0.16 240)',
                    'metric' => 'pitch',
                    'group' => 'navigation',
                    'type' => 'signed',
                    'related' => ['heel'],
                ],
                'trip_log' => [
                    'label' => 'Trip Log',
                    'unit' => 'nm',
                    'color' => 'oklch(0.42 0.14 178)',
                    'metric' => 'trip_log',
                    'group' => 'navigation',
                    'type' => 'standard',
                ],
                'nav_wp_distance' => [
                    'label' => 'Distance to Waypoint',
                    'unit' => 'nm',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'nav_wp_distance',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['nav_wp_ttg'],
                ],
                'nav_wp_ttg' => [
                    'label' => 'Time to Waypoint',
                    'unit' => 's',
                    'color' => 'oklch(0.60 0.16 240)',
                    'metric' => 'nav_wp_ttg',
                    'group' => 'navigation',
                    'type' => 'duration',
                    'related' => ['nav_wp_distance'],
                ],
                'vmg' => [
                    'label' => 'VMG',
                    'unit' => 'kn',
                    'color' => 'oklch(0.58 0.18 160)',
                    'metric' => 'vmg',
                    'group' => 'navigation',
                    'type' => 'standard',
                    'related' => ['speed', 'nav_wp_distance'],
                ],

                'wind_speed_true' => [
                    'label' => 'True Wind Speed',
                    'unit' => 'kn',
                    'color' => 'oklch(0.54 0.22 27)',
                    'computed' => 'true_wind_speed',
                    'group' => 'wind',
                    'type' => 'standard',
                    'related' => ['wind_speed_apparent', 'wind_direction_true'],
                ],
                'wind_direction_true' => [
                    'label' => 'True Wind Direction',
                    'unit' => '°',
                    'color' => 'oklch(0.65 0.18 40)',
                    'computed' => 'true_wind_direction',
                    'group' => 'wind',
                    'type' => 'compass',
                    'related' => ['wind_angle_apparent', 'wind_speed_true'],
                ],
                'wind_speed_apparent' => [
                    'label' => 'Apparent Wind Speed',
                    'unit' => 'kn',
                    'color' => 'oklch(0.60 0.16 330)',
                    'metric' => 'wind_speed_apparent',
                    'group' => 'wind',
                    'type' => 'standard',
                    'related' => ['wind_speed_true', 'wind_angle_apparent'],
                ],
                'wind_angle_apparent' => [
                    'label' => 'Apparent Wind Angle',
                    'unit' => '°',
                    'color' => 'oklch(0.60 0.16 330)',
                    'metric' => 'wind_angle_apparent',
                    'group' => 'wind',
                    'type' => 'compass',
                    'related' => ['wind_direction_true', 'wind_speed_apparent'],
                ],

                'battery_soc' => [
                    'label' => 'Battery SOC',
                    'unit' => '%',
                    'color' => 'oklch(0.62 0.15 155)',
                    'metric' => 'house_battery_soc',
                    'group' => 'power',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['battery_voltage', 'battery_power', 'battery_current'],
                ],
                'battery_power' => [
                    'label' => 'Battery Power',
                    'unit' => 'W',
                    'color' => 'oklch(0.62 0.15 155)',
                    'computed' => 'battery_power',
                    'group' => 'power',
                    'type' => 'signed',
                    'related' => ['battery_voltage', 'battery_soc', 'battery_current'],
                ],
                'battery_voltage' => [
                    'label' => 'Battery Voltage',
                    'unit' => 'V',
                    'color' => 'oklch(0.62 0.15 155)',
                    'metric' => 'house_battery_voltage',
                    'group' => 'power',
                    'type' => 'standard',
                    'related' => ['battery_soc', 'engine_battery_voltage'],
                ],
                'battery_current' => [
                    'label' => 'Battery Current',
                    'unit' => 'A',
                    'color' => 'oklch(0.65 0.18 40)',
                    'metric' => 'house_battery_current',
                    'group' => 'power',
                    'type' => 'signed',
                    'related' => ['battery_power', 'battery_voltage'],
                ],
                'engine_battery_voltage' => [
                    'label' => 'Engine Battery',
                    'unit' => 'V',
                    'color' => 'oklch(0.65 0.18 40)',
                    'metric' => 'engine_battery_voltage',
                    'group' => 'power',
                    'type' => 'standard',
                    'related' => ['battery_voltage'],
                ],

                'temp_main_cabin' => [
                    'label' => 'Temp: Main Cabin',
                    'unit' => '°C',
                    'color' => 'oklch(0.65 0.18 330)',
                    'metric' => 'cabin_temp_main',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_forepeak', 'temp_quarterberth'],
                ],
                'temp_forepeak' => [
                    'label' => 'Temp: Forepeak',
                    'unit' => '°C',
                    'color' => 'oklch(0.70 0.14 70)',
                    'metric' => 'cabin_temp_forepeak',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_main_cabin', 'temp_quarterberth'],
                ],
                'temp_quarterberth' => [
                    'label' => 'Temp: Quarterberth',
                    'unit' => '°C',
                    'color' => 'oklch(0.60 0.16 240)',
                    'metric' => 'cabin_temp_quarterberth',
                    'group' => 'cabin',
                    'type' => 'standard',
                    'related' => ['temp_main_cabin', 'temp_forepeak'],
                ],
                'humidity_forepeak' => [
                    'label' => 'Humidity: Forepeak',
                    'unit' => '%',
                    'color' => 'oklch(0.70 0.14 70)',
                    'metric' => 'cabin_humidity_forepeak',
                    'group' => 'cabin',
                    'type' => 'gauge',
                    'related' => ['humidity_main_cabin', 'humidity_quarterberth'],
                ],
                'humidity_quarterberth' => [
                    'label' => 'Humidity: Quarterberth',
                    'unit' => '%',
                    'color' => 'oklch(0.60 0.16 240)',
                    'metric' => 'cabin_humidity_quarterberth',
                    'group' => 'cabin',
                    'type' => 'gauge',
                ],
                'humidity_main_cabin' => [
                    'label' => 'Humidity: Main Cabin',
                    'unit' => '%',
                    'color' => 'oklch(0.65 0.18 330)',
                    'metric' => 'cabin_humidity_main',
                    'group' => 'cabin',
                    'type' => 'gauge',
                ],
                'pressure_forepeak' => [
                    'label' => 'Barometric Pressure',
                    'unit' => 'hPa',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'cabin_pressure_forepeak',
                    'group' => 'cabin',
                    'type' => 'standard',
                ],

                'water_temp' => [
                    'label' => 'Sea Water Temperature',
                    'unit' => '°C',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'water_temp',
                    'group' => 'environment',
                    'type' => 'standard',
                ],

                'fuel_level' => [
                    'label' => 'Diesel',
                    'unit' => '%',
                    'color' => 'oklch(0.48 0.17 70)',
                    'metric' => 'fuel_level',
                    'group' => 'tanks',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['water_level'],
                ],
                'water_level' => [
                    'label' => 'Fresh Water',
                    'unit' => '%',
                    'color' => 'oklch(0.42 0.14 245)',
                    'metric' => 'water_level',
                    'group' => 'tanks',
                    'type' => 'gauge',
                    'dashboard_indicator' => 'level_bar',
                    'related' => ['fuel_level'],
                ],

                'gps_satellites' => [
                    'label' => 'GPS Satellites',
                    'unit' => '',
                    'color' => 'oklch(0.62 0.15 155)',
                    'metric' => 'gps_satellites',
                    'group' => 'tracker',
                    'type' => 'standard',
                ],
                'lte_rssi' => [
                    'label' => 'LTE Signal',
                    'unit' => 'dBm',
                    'color' => 'oklch(0.54 0.22 27)',
                    'metric' => 'tracker_lte_rssi',
                    'group' => 'tracker',
                    'type' => 'standard',
                    'related' => ['wifi_rssi'],
                ],
                'wifi_rssi' => [
                    'label' => 'WiFi Signal',
                    'unit' => 'dBm',
                    'color' => 'oklch(0.55 0.15 240)',
                    'metric' => 'tracker_wifi_rssi',
                    'group' => 'tracker',
                    'type' => 'standard',
                    'related' => ['lte_rssi'],
                ],
                'cpu_usage' => [
                    'label' => 'CPU Usage',
                    'unit' => '%',
                    'color' => 'oklch(0.60 0.16 330)',
                    'metric' => 'tracker_cpu',
                    'group' => 'tracker',
                    'type' => 'gauge',
                ],
            ],

            'explore_groups' => [
                'navigation' => [
                    'label' => 'Navigation',
                    'color' => 'oklch(0.42 0.14 178)',
                    'expanded' => true,
                ],
                'wind' => [
                    'label' => 'Wind',
                    'color' => 'oklch(0.48 0.17 70)',
                    'expanded' => false,
                    'headlines' => ['wind_speed_true', 'wind_direction_true', 'wind_speed_apparent', 'wind_angle_apparent'],
                ],
                'power' => [
                    'label' => 'Power',
                    'color' => 'oklch(0.45 0.16 150)',
                    'expanded' => true,
                ],
                'tanks' => [
                    'label' => 'Tanks',
                    'color' => 'oklch(0.48 0.17 70)',
                    'expanded' => true,
                ],
                'cabin' => [
                    'label' => 'Cabin',
                    'color' => 'oklch(0.48 0.17 70)',
                    'expanded' => false,
                    'headlines' => ['temp_main_cabin', 'temp_forepeak', 'pressure_forepeak'],
                ],
                'environment' => [
                    'label' => 'Environment',
                    'color' => 'oklch(0.42 0.14 245)',
                    'expanded' => false,
                    'headlines' => ['water_temp'],
                ],
                'tracker' => [
                    'label' => 'Tracker',
                    'color' => 'oklch(0.52 0.014 205)',
                    'expanded' => false,
                    'headlines' => ['gps_satellites', 'lte_rssi', 'cpu_usage'],
                ],
            ],
        ],
    ],
];
