logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: :9997

authMethod: internal
authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
        path:
      - action: read
        path:
      - action: playback
        path:
  - user: any
    pass:
    ips: []
    permissions:
      - action: api
      - action: metrics
      - action: pprof

srt: yes
srtAddress: :8890

rtsp: yes
rtspAddress: :8554
rtspTransports: [tcp]

webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigins: ["*"]
webrtcICEServers2: []

hls: yes
hlsAddress: :8888
hlsAllowOrigins: ["*"]
hlsAlwaysRemux: yes
hlsCDNSecret: "scarlet-hls-internal"

paths:
  live:
    source: publisher
