logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: :9997

srt: yes
srtAddress: :8890

rtsp: yes
rtspAddress: :8554
rtspTransports: [tcp]

webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigins: ["*"]
webrtcICEServers2: []

hls: yes
hlsAddress: :8888
hlsAllowOrigins: ["*"]
hlsAlwaysRemux: yes

paths:
  live:
    source: publisher
