extensions:
  bearertokenauth:
    token: "${OTEL_AUTH_TOKEN}"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: bearertokenauth
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: bearertokenauth

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 5s
    limit_mib: 256
    spike_limit_mib: 64

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: scarlet
    send_timestamps: true
    resource_to_telemetry_conversion:
      enabled: true
    metric_expiration: 10m

  prometheusremotewrite:
    endpoint: http://victoriametrics:8428/api/v1/write
    namespace: scarlet
    resource_to_telemetry_conversion:
      enabled: true
    tls:
      insecure: true

service:
  extensions: [bearertokenauth]

  telemetry:
    logs:
      level: warn

  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, prometheusremotewrite]
